### PR TITLE
Great new testing view

### PR DESCRIPTION
**Pull request by profbetis**

### CODE REVIEW

**Comment by binary132** [comment]
:clap: :astonished:

**Comment by binary132** [comment]
@profbetis the problem is with the broken `fetch-updates` we can't work properly on `index.html`.  So I'm not comfortable merging the `fetch-updates` code until it's finished.  There are also a bunch of junk commits (my `WIP` commits) which need to be rebased into a meaningful feature commit when the `fetch-updates` feature is at least passing tests.  Otherwise we'll end up with a cluttered and illegible `master` history.

Just swap it out for the static tasks map.  When it's ready, my feature will nearly be a seamless drop-in replacement.

---

We should not do master-to-master merges.  Do a `git checkout -b <branchname>` to copy your branch, and make a pull request against that instead.

---

If we can split this up into a few smaller feature-complete branches (like `feature-test-styling`, `feature-fetch-updates`) that would be ideal.  Then we could also link them to Asana or Pivotal stories.

---

The idea is that when reviewing `master`'s history we should see a clear, detailed log of the features we added.  I advise following [this commit style guide](https://github.com/erlang/otp/wiki/Writing-good-commit-messages), which adheres to the official Git documentation.

---

Otherwise, looks dope!  I can walk you through the rebasing stuff this afternoon.

**Comment by binary132** [comment]
Also wanted to ask how the styling works when you add more namespaces, it's all left-justified now.

We should also think about making a mobile-responsive design at some point, tho I don't think that's important for the test view.

**Comment by profbetis** [comment]
Re: more namespaces
It's set up in a column layout for now specified by width. It will try to divide the space into as any columns no smaller than the specified width. I can try modifying this to always be a fixed number of columns instead, but they will be longer and less legible. I think specifying width is a more consistent option, but we can experiment.

**Pull request closed without merging**
